#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing pdiocertificate libs ..."
COMMAND=$(cat <<EOF
apt-get install -y -q --no-install-recommends \
    openjdk-11-jdk \
    ghostscript \
    poppler-utils \
    fontconfig \
    libfontconfig1-dev \
    libfreetype6-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    xfonts-base \
    xfonts-75dpi \
    fonts-freefont-ttf \
    fonts-liberation \
   ttf-dejavu
echo "-----> pdiocertificate installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
